server:
  port: 8090

spring:
  application:
    name: SistemaVoluntariado
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    plataform: postgres
    driver-class-name: org.postgresql.Driver
    dbname: SistemaVoluntariado
    url: jdbc:postgresql://localhost:5432/SistemaVoluntariado
    username: postgres
    password: Simon_789